// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import {Test} from "forge-std/Test.sol";
import {ReservesOracle} from "../../../src/oracles/ReservesOracle.sol";
import {BondOracle} from "../../../src/oracles/BondOracle.sol";
import {ReservesFunctionsConsumer} from "../../../src/oracles/ReservesFunctionsConsumer.sol";
import {BondFunctionsConsumer} from "../../../src/oracles/BondFunctionsConsumer.sol";
import {DeployOracles} from "../../../script/DeployOracles.s.sol";
import {IBondAutomation} from "../../../src/interfaces/IBondAutomation.sol";
import {IReservesAutomation} from "../../../src/interfaces/IReservesAutomation.sol";
import {HelperConfig} from "../../../script/HelperConfig.sol";
import {MockFunctionsRouter} from "../../mocks/MockFunctionsRouter.sol";
import {BondYieldsResponse, ReservesResponse} from "../../../src/types.sol";
import {OracleDataExamples} from "../../OracleDataExamples.sol";

abstract contract BaseTest is Test {
    ReservesOracle reservesOracle;
    BondOracle bondOracle;
    ReservesFunctionsConsumer reservesFunctionsConsumer;
    BondFunctionsConsumer bondFunctionsConsumer;
    IBondAutomation bondAutomationInterface;
    IReservesAutomation reservesAutomationInterface;
    MockFunctionsRouter mockFunctionsRouter;

    address bondAutomation;
    address reservesAutomation;
    address bondForwarder;
    address reservesForwarder;

    uint256 interval;
    uint256 gracePeriod;

    function setUp() public virtual {

        HelperConfig helperConfig = new HelperConfig();
        (,,, mockFunctionsRouter) = helperConfig.getMocks();

        // Deploy oracles and consumers
        DeployOracles deployScript = new DeployOracles();
        (bondOracle, reservesOracle, bondFunctionsConsumer, 
            reservesFunctionsConsumer, bondAutomationInterface, reservesAutomationInterface, 
            , , bondForwarder, reservesForwarder) = deployScript.run();

        bondAutomation = address(bondAutomationInterface);
        reservesAutomation = address(reservesAutomationInterface);

        interval = bondAutomationInterface.getInterval();
        gracePeriod = bondAutomationInterface.getGracePeriod();
    }   

    /// @dev Helper that simulates the async Chainlink Functions flow:
    ///      1. bondAutomation triggers sendRequest (has AUTOMATION_ROLE)
    ///      2. Warps 10 minutes forward to simulate DON processing time
    ///      3. MockFunctionsRouter fulfills the request with the provided values
    /// @param yieldsData   BondYieldsResponse struct; decomposed into [2Y,5Y,10Y,30Y] array + timestamp
    /// @param err          Error bytes; if non-empty, response body is left empty (mirrors Chainlink behaviour)
    /// @return requestId   The requestId generated by the mock router
    function _sendRequestAndFulfillBondFunctionsConsumer(
        BondYieldsResponse memory yieldsData,
        bytes memory err
    ) internal returns (bytes32 requestId) {
        // bondAutomation holds AUTOMATION_ROLE on bondFunctionsConsumer
        vm.prank(bondAutomation);
        requestId = bondFunctionsConsumer.sendRequest();

        // Simulate async DON processing time (~10 minutes)
        vm.warp(block.timestamp + 10 minutes);

        // Decompose the struct into the array format expected by _fulfillRequest
        uint256[] memory yields = new uint256[](4);
        yields[0] = yieldsData.twoYearYield;
        yields[1] = yieldsData.fiveYearYield;
        yields[2] = yieldsData.tenYearYield;
        yields[3] = yieldsData.thirtyYearYield;

        // Encode the response the same way the Chainlink Functions DON would
        bytes memory response = err.length == 0
            ? abi.encode(yields, yieldsData.timestamp)
            : bytes("");

        // Fulfill the pending request via the mock router
        mockFunctionsRouter.fulfillRequest(requestId, response, err);
    }

    /// @dev Helper that simulates the async Chainlink Functions flow for reserves:
    ///      1. reservesAutomation triggers sendRequest (has AUTOMATION_ROLE)
    ///      2. Warps 10 minutes forward to simulate DON processing time
    ///      3. MockFunctionsRouter fulfills the request with the provided values
    /// @param reservesData  ReservesResponse struct; decomposed into bond[4], cash[4] arrays + timestamp
    /// @param signature     SPV signature bytes included in the encoded response
    /// @param err           Error bytes; if non-empty, response body is left empty (mirrors Chainlink behaviour)
    /// @return requestId    The requestId generated by the mock router
    function _sendRequestAndFulfillReservesFunctionsConsumer(
        ReservesResponse memory reservesData,
        bytes memory signature,
        bytes memory err
    ) internal returns (bytes32 requestId) {
        // reservesAutomation holds AUTOMATION_ROLE on reservesFunctionsConsumer
        vm.prank(reservesAutomation);
        requestId = reservesFunctionsConsumer.sendRequest();

        // Simulate async DON processing time (~10 minutes)
        vm.warp(block.timestamp + 10 minutes);

        // Decompose the struct into the fixed-size arrays expected by _fulfillRequest
        uint256[4] memory bond;
        bond[0] = reservesData.twoYearUsdBondsValue;
        bond[1] = reservesData.fiveYearUsdBondsValue;
        bond[2] = reservesData.tenYearUsdBondsValue;
        bond[3] = reservesData.thirtyYearUsdBondsValue;

        uint256[4] memory cash;
        cash[0] = reservesData.twoYearUsdCashValue;
        cash[1] = reservesData.fiveYearUsdCashValue;
        cash[2] = reservesData.tenYearUsdCashValue;
        cash[3] = reservesData.thirtyYearUsdCashValue;

        // Encode the response the same way the Chainlink Functions DON would
        bytes memory response = err.length == 0
            ? abi.encode(bond, cash, reservesData.timestamp, signature)
            : bytes("");

        // Fulfill the pending request via the mock router
        mockFunctionsRouter.fulfillRequest(requestId, response, err);
    }

}